server:
  port: 8762

spring:
  application:
    name: zuul-server

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:10000/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"