server: 
  port: 9090

#Searching config git repository
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rogeriotakashi/springboot-microservice-config
  application:
    name: configserver

